http_port 3128

acl lab_agents src 172.30.0.0/24
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

acl denied_destinations dst "/etc/squid/lan.denylist.txt"
acl allowed_domains dstdomain "/etc/squid/allowlist.txt"
acl raw_ip_host dstdom_regex -i ^[0-9]+(\.[0-9]+){3}$ ^\[[0-9A-Fa-f:.]+\]$

http_access deny !lab_agents
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny denied_destinations
http_access deny raw_ip_host
http_access allow lab_agents allowed_domains
http_access deny all

access_log /var/log/squid/access.log squid
cache_log /var/log/squid/cache.log
cache_store_log none

cache deny all
cache_mem 0 MB
maximum_object_size 0 KB
minimum_object_size 0 KB

pid_filename /run/squid.pid
coredump_dir /var/spool/squid
