#!/usr/bin/env bash
# tools/render-adapters.sh — generate the per-tool allow/deny rule BODIES from shared policy, so the
# three adapters are never hand-maintained. Single policy source:
#   - policy/allow.commands   -> the auto-approve allow set (translated per tool)
#   - policy/protected.paths  -> rail Edit/Write denies (Claude/Grok)
#   - GIT_DENY below          -> neutral mirror of policy/deny.patterns for the NATIVE belt-and-
#                               suspenders rules (the guard, tools/pretooluse-guard.sh, is the
#                               AUTHORITATIVE denier; keep this list in sync when adding a denial).
#
# Generated files (do not hand-edit the marked/whole regions):
#   .claude/settings.json          (whole file — strict JSON, no comments)
#   .codex/rules/agent-lab.rules   (whole file — execpolicy prefix_rule; token-based)
#   .grok/config.toml              (whole file — [permission] + [ui])
#
# Codex notes: execpolicy is TOKEN-prefix, so path-prefixes (./scripts/dev/) and remote refs
# (origin/*) cannot be expressed as rules — the guard enforces those; workspace-write auto-runs
# in-workspace commands. 'git fetch' is omitted for Codex (network-off by design, v1).
#
# Idempotent. Run as a maintenance task:  AGENT_LAB_MAINTENANCE=1 tools/render-adapters.sh
set -euo pipefail
root="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
cd "$root"
command -v jq >/dev/null 2>&1 || { echo "render-adapters: jq is required" >&2; exit 1; }

mapfile -t ALLOW < <(grep -vE '^[[:space:]]*(#|$)' policy/allow.commands)
mapfile -t PROT < <(grep -vE '^[[:space:]]*(#|$)' policy/protected.paths)

# Neutral remote-integrity deny heads — MIRROR of policy/deny.patterns (guard is authoritative).
GIT_DENY=(
  "git push" "git pull"
  "git merge origin/" "git merge upstream/" "git rebase origin/" "git rebase upstream/"
  "gh pr" "gh release"
  "git remote add" "git remote set-url" "git remote remove" "git remote rename"
)

toks() { # "git commit" -> "git", "commit"
  printf '%s' "$1" | awk '{for(i=1;i<=NF;i++) printf "%s\"%s\"",(i>1?", ":""),$i}'
}

# ---------------- Claude: whole settings.json via jq (guarantees valid JSON) ----------------
emit_claude() {
  local allow=() deny=() c d
  for c in "${ALLOW[@]}"; do allow+=("Bash(${c}:*)"); done
  allow+=("Read(**)" "Edit(**)" "Write(**)")
  for d in "${GIT_DENY[@]}"; do
    case "$d" in
      */) deny+=("Bash(${d}*)") ;;                      # glob form for remote-ref denies
      *)  deny+=("Bash(${d}:*)" "Bash(${d})") ;;
    esac
  done
  # NOTE: protected-path Edit/Write denies are intentionally NOT emitted for Claude. Claude's native
  # permissions.deny has NO maintenance bypass, so a native Edit(rail) deny self-locks even sanctioned
  # maintenance (the §13.9 self-lock; see docs/agent-config.md). The guard's Edit|Write matcher
  # enforces rail read-only WITH the AGENT_LAB_MAINTENANCE bypass; the git/remote denies above keep
  # their native belt-and-suspenders. Secret reads stay natively denied (never needed for maintenance).
  deny+=("Read(./.env)" "Read(./.env.*)" "Read(./secrets/**)")

  local guard='bash "$(git rev-parse --show-toplevel)/tools/pretooluse-guard.sh"'
  local boot='bash "$(git rev-parse --show-toplevel)/tools/session-bootstrap.sh" claude'
  mkdir -p .claude
  jq -n \
    --argjson allow "$(printf '%s\n' "${allow[@]}" | jq -R . | jq -s .)" \
    --argjson deny "$(printf '%s\n' "${deny[@]}" | jq -R . | jq -s .)" \
    --arg guard "$guard" --arg boot "$boot" \
    '{
      "$schema": "https://json.schemastore.org/claude-code-settings.json",
      permissions: { defaultMode: "acceptEdits", allow: $allow, deny: $deny },
      hooks: {
        PreToolUse: [
          { matcher: "Bash", hooks: [ { type: "command", command: $guard } ] },
          { matcher: "Edit|Write|MultiEdit|NotebookEdit", hooks: [ { type: "command", command: $guard } ] }
        ],
        SessionStart: [
          { matcher: "startup|resume", hooks: [ { type: "command", command: $boot } ] }
        ]
      }
    }' > .claude/settings.json
}

# ---------------- Codex: execpolicy rules (token-based) ----------------
emit_codex() {
  local c d
  mkdir -p .codex/rules
  {
    echo "# >>> GENERATED by tools/render-adapters.sh — DO NOT EDIT (edit policy/* and re-run) >>>"
    echo "# Codex execpolicy: allow local git + forbid remote git/PR. The PreToolUse guard"
    echo "# (tools/pretooluse-guard.sh) is the AUTHORITATIVE denier; these are belt-and-suspenders."
    echo "# Token-based: path-prefixes and origin/* refs are guard-enforced, not expressible here."
    echo "# CODEX_V1: 'git fetch' intentionally omitted — workspace-write sandbox is network-off."
    echo
    echo "# -- allow: local git (clean token prefixes only; workspace-write auto-runs the rest) --"
    for c in "${ALLOW[@]}"; do
      case "$c" in
        "git fetch") echo "# CODEX_V1: [\"git\",\"fetch\"] N/A — network-off" ;;
        git\ *) printf 'prefix_rule(pattern = [%s], decision = "allow", justification = "agent-lab local-git set")\n' "$(toks "$c")" ;;
        shellcheck) printf 'prefix_rule(pattern = ["shellcheck"], decision = "allow", justification = "agent-lab lint")\n' ;;
      esac
    done
    echo
    echo "# -- forbidden: remote integrity --"
    for d in "${GIT_DENY[@]}"; do
      case "$d" in
        */) echo "# guard-enforced (remote ref, not a token prefix): $d*" ;;
        *) printf 'prefix_rule(pattern = [%s], decision = "forbidden", justification = "agent-lab: the human owns the remote/PR")\n' "$(toks "$d")" ;;
      esac
    done
    echo "# <<< END GENERATED <<<"
  } > .codex/rules/agent-lab.rules
}

# ---------------- Grok: whole config.toml ([permission] + [ui]) ----------------
emit_grok() {
  local c d
  mkdir -p .grok
  {
    echo "# >>> GENERATED by tools/render-adapters.sh — DO NOT EDIT (edit policy/* and re-run) >>>"
    echo "# Grok Build project config. Decision order: PreToolUse hooks -> deny>ask>allow -> fast"
    echo "# paths -> prompt. deny survives always-approve. Guard (tools/pretooluse-guard.sh) is"
    echo "# authoritative; these rules are belt-and-suspenders. Hooks are wired in .grok/hooks/."
    echo
    echo "# Autonomy posture is set by the OPERATOR at launch — NOT here. Grok treats [ui] permission_mode"
    echo "# as a global/user default that can leak across projects, and 'always-approve' is a launch FLAG,"
    echo "# not a config enum (valid config enum: default|acceptEdits|auto|dontAsk|bypassPermissions|plan)."
    echo "# Launch:  grok --always-approve   — the deny rules below + the PreToolUse hook still hold (Grok"
    echo "# runs hooks -> deny>allow -> fast-paths before any prompt-skip). See docs/agent-config.md."
    echo
    echo "[permission]"
    echo "deny = ["
    for d in "${GIT_DENY[@]}"; do printf '  "Bash(%s*)",\n' "$d"; done
    for p in "${PROT[@]}"; do
      case "$p" in
        */) printf '  "Edit(%s**)", "Write(%s**)",\n' "$p" "$p" ;;
        *) printf '  "Edit(%s)", "Write(%s)",\n' "$p" "$p" ;;
      esac
    done
    echo ']'
    echo "allow = ["
    for c in "${ALLOW[@]}"; do printf '  "Bash(%s*)",\n' "$c"; done
    echo '  "Read(**)", "Edit(**)", "Write(**)",'
    echo ']'
    echo "# <<< END GENERATED <<<"
  } > .grok/config.toml
}

emit_claude
emit_codex
emit_grok
echo "render-adapters: wrote .claude/settings.json .codex/rules/agent-lab.rules .grok/config.toml"
